# Deploy package documentation to github pages on each push to main branch (or triggered manually)
name: documentation

on:
  push:
    branches: [main, SVH-fix-docs]
  workflow_dispatch:

jobs:
  documentation:
    runs-on: ubuntu-latest
  permissions:
    contents: write

    steps:
    - uses: actions/checkout@v3
      with: {fetch-depth: 0}  # deep clone for setuptools-scm
    #- name: Get all git tags
    #run: git fetch --prune --unshallow --tags
    - name: Set up Python 3.10
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        cache: 'pip'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install tox
    - name: Build documentation
      run: |
        tox -e docs
    - name: Deploy documentation
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./docs/_build/html